spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/postgres
  jpa:
    hibernate:
      ddl-auto: create